# Generated by Django 3.2.23 on 2023-11-12 18:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231113_0021'),
    ]

    operations = [
    ]
