# Generated by Django 3.2.23 on 2023-11-12 19:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_account_no'),
    ]

    operations = [

    ]
