# Generated by Django 3.2.23 on 2023-11-13 15:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20231113_1533'),
    ]

    operations = [
       
        
    ]
